[package]
name = "dirichlet_fit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
rand = "*"
rand_xoshiro = "*"

[dev-dependencies]
rand_distr = "*"
env_logger = "*"
